### ISSUE TITLE
Ugly commits in branch origin/6

### ISSUE THREAD

**Issue by wundo** [Gizra/message#10]
What is the branch origin/6 about?
Those commits look freaking ugly.... ;(

| \* 8780e7d - (3 weeks ago) Push new test. - Roy Segall
| \* fb0a995 - (3 weeks ago) Try something. - Roy Segall
| \* 780038d - (3 weeks ago) Try? - Roy Segall
| \* 137fbb0 - (3 weeks ago) Foo. - Roy Segall
| \* 9f999fd - (3 weeks ago) bbbb - Roy Segall
| \* 51ea82f - (3 weeks ago) serizlie. - Roy Segall
| \* b5980f7 - (3 weeks ago) dd - Roy Segall
| \* 11bf456 - (3 weeks ago) fff - Roy Segall
| \* e4e031f - (3 weeks ago) ff - Roy Segall
| \* 9b1db0c - (3 weeks ago) fo - Roy Segall
| \* 2248317 - (3 weeks ago) ffff - Roy Segall
| \* 31dbdac - (3 weeks ago) fff - Roy Segall
| \* 878d2eb - (3 weeks ago) Try. - Roy Segall
| \* a0b22d7 - (3 weeks ago) f - Roy Segall
| \* af37611 - (3 weeks ago) anither try. - Roy Segall
| \* 3963d6d - (3 weeks ago) Try 5.4 - Roy Segall
| \* 0692357 - (4 weeks ago) Surfing bird. - Roy Segall
| \* 8c8d637 - (4 weeks ago) Push. - Roy Segall
| \* 8ded72d - (4 weeks ago) Maybe.... - Roy Segall
| \* 26b4219 - (4 weeks ago) Try. - Roy Segall
| \* dae7595 - (4 weeks ago) hmmm - Roy Segall
| \* 7752ad2 - (4 weeks ago) Maybe? - Roy Segall
| \* 8c21f2d - (4 weeks ago) Organize? - Roy Segall
| \* ceaaa0f - (4 weeks ago) RRR - Roy Segall
| \* 2d2953a - (4 weeks ago) Available types. - Roy Segall
| \* 52e2120 - (4 weeks ago) bar - Roy Segall
| \* 1fe9e3d - (4 weeks ago) foo - Roy Segall
| \* d387415 - (4 weeks ago) foo. - Roy Segall
| \* 590d23e - (4 weeks ago) Pushing debug. - Roy Segall

**Comment by amitaibu** [comment]
Those commits are going to be `merge --squash` anyway.

**Comment by wundo** [comment]
Ok, I was just scared while looking at the logs...
