### ISSUE TITLE
Some base methods not working: setOwnerId, setCreatedTime

### ISSUE THREAD

**Issue by mccrodp** [Gizra/message#108]
I am pretty sure that the above methods are not working and while perhaps related, I believe `getOwnerId()` is not working either.

I noticed this as after calling these methods in `submitForm()` in Message UI the entity object does not reflect the new values, either on a new or existing message entity. See usage in: https://github.com/mccrodp/message_ui/blob/8.x-1.x/src/Form/MessageForm.php#L178

When stepping through this it seems to behave differently than the node entity when it calls it's `setOwnerId()` for instance.

**Comment by mccrodp** [comment]
When we looked at this earlier, it seemed to be setting the 'uid' value in the nested array in 'values' on the Message entity. It did not set the value directly on the Message. i.e. - `$message->uid` not set, shouldn't it set both?

**Comment by mccrodp** [comment]
This is now evident in the PR: https://github.com/Gizra/message/pull/107 where we have a new `MessageCreateTest` which tests `$this->assertEqual($this->user->id(), $message->getOwnerId(), 'The default value for uid was set correctly.');` after calling `$message->save()`.

After calling save on a message we can see the output attached. The mid, uid, etc. are not set, but the uid we can see set in the values array. Is there something that returns the mid and other values later in the process? I'm unsure of this, but as originally stated, this is not the same as happens when checking node object after `$node->save()`.

<img width="351" alt="message-object-post-save" src="https://cloud.githubusercontent.com/assets/559938/16354975/275dd994-3aa9-11e6-91a2-a4720737d6e2.png">

**Comment by jhedstrom** [comment]
The `setOwnerId()` issue should be resolved by #130.

**Comment by jhedstrom** [comment]
In manual testing via `drush php`, the `setCreatedTime()` method appears to be working:

<img width="528" alt="screen shot 2016-10-14 at 9 54 07 am" src="https://cloud.githubusercontent.com/assets/76833/19395777/46fb458c-91f4-11e6-8368-be7e6fa8234d.png">

**Comment by amitaibu** [comment]
wow, what's that REPL?

**Comment by jhedstrom** [comment]
Psy shell...part of the latest Drush, via `drush php` =)
