### ISSUE TITLE
Is the drupal.org Documentation up to date? 

### ISSUE THREAD

**Issue by wundo** [Gizra/message#11]
It doesn't look so for me, it makes a lot of mentions to interfaces that aren't shipped with message.module anymore :(

**Comment by amitaibu** [comment]
It should be updated, yes. Which interfaces for example?

**Comment by wundo** [comment]
This one mostly: https://www.drupal.org/node/2180167

**Comment by amitaibu** [comment]
That screen is still there (`admin/structure/messages`)

**Comment by wundo** [comment]
message module is enabled but SELECT \* FROM menu_router where path LIKE 'admin/structure/messages'

returns empty :(

**Comment by amitaibu** [comment]
On a clean Drupal7?

**Comment by wundo** [comment]
Yes

**Comment by wundo** [comment]
Do I need message_ui for it to work?

**Comment by amitaibu** [comment]
> Do I need message_ui for it to work?

No, but i'm not familiar with this issue. Doesn't sound like Message specific.

**Comment by wundo** [comment]
It was something related with being in a older version, fixed now!
