### ISSUE TITLE
Cannot use Drupal\Component\Utility\String as String because 'String' is a special class name

### ISSUE THREAD

**Issue by SOLUTIONS-AT** [Gizra/message#110]
Installed Message for the first time on 8.2.x-dev and PHP 7.0.7 resulting in WSOD

PHP Fatal error:  Cannot use Drupal\Component\Utility\String as String because 'String' is a special class name in /home/solution/public_html/my-domain.com/modules/contrib/message/modules/message_example/message_example.tokens.inc on line 8

**Comment by amitaibu** [comment]
@DavidHernandez in case you'r looking for some D8 contributions... 😉
