### ISSUE TITLE
Argument 3 passed to MessagePurgeOrchestrator::purgeMessagesByTemplate() must be of the type array

### ISSUE THREAD

**Issue by mccrodp** [Gizra/message#119]
On Drupal 8 when uninstalling the `message_ui` I get the following error (when message is still enabled). This one could be on `message_ui` but I'm not sure why this would be happening, so I'll look into it later.

```
Argument 3 passed to Drupal\message\MessagePurgeOrchestrator::purgeMessagesByTemplate() must be of the type array, null[error]
given, called in /Applications/MAMP/htdocs/drupal-8/modules/message/src/MessagePurgeOrchestrator.php on line 95 and
defined MessagePurgeOrchestrator.php:112
```

**Comment by kevin-dutra** [comment]
For me, it also occurs every cron run.

**Comment by jhedstrom** [comment]
This is actually an issue with configs saved that predate #100. To fix using drush:

`drush cedit message.settings` and then make sure this line appears:

``` yaml
purge_methods: {  }
```

Any other purge-related lines can be removed.

In patch form:

```
-purge_enable: true
-purge_quota: 0
-purge_days: 0
+purge_methods: {  }
```
