### ISSUE TITLE
Add kernel tests to Message::getText

### ISSUE THREAD

**Issue by amitaibu** [Gizra/message#120]
https://github.com/Gizra/message/blob/22e2a0fb93565459117c23a307ca457f0aa2a3b3/src/Entity/Message.php#L235

@DavidHernandez want to give it a stab? 😄

**Comment by DavidHernandez** [comment]
@amitaibu sure, let's try it!

**Comment by jhedstrom** [comment]
Over in #123 I suggested not allowing message templates to be deleted if messages exist that are using them.

However, when reviewing this method for unit testing:

``` php
    if (!$message_template = $this->getTemplate()) {
      // Message template does not exist any more.
      // We don't throw an exception, to make sure we don't break sites that
      // removed the message template, so we silently ignore.
      return [];
    }
```

That code seems at odds with my suggestion. Should this instead throw an exception, or use an assertion that the message template still exists?

**Comment by amitaibu** [comment]
Well, in D7 I wanted to prevent a site from breaking, because a message-template was (somehow) removed.

While I like your suggestion from #123, as it's inline with how core does stuff, I think having the above mentioned code is still ok. That is, if the message template was programatically deleted, we don't want to fail the site.

I can be talked out of this, if you feel that an exception would be more appropriate.

**Comment by jhedstrom** [comment]
I'm going to try and tackle this as part of #140.

**Comment by jhedstrom** [comment]
I've updated this to add kernel tests instead. As I mentioned in the PR, mocking half of the entity manager service won't really gain us the typical insurance a unit test would provide that things are working as expected. I'll update that PR with a comprehensive kernel test.
