### ISSUE TITLE
Message Example field config already exists in config error

### ISSUE THREAD

**Issue by mccrodp** [Gizra/message#121]
I get the below on Drupal 8.1.7 when installing message_example, creating a message of one of the types, uninstalling the module, then re-enabling it.

My work around was make the config in this module exist in "optional" folder rather than install. Is this a viable change to be added via a PR, or should the module's uninstall hook clean up in some way to avoid this?

``` shell
The following extensions will be enabled: message_example
Do you really want to continue? (y/n): y
exception 'Drupal\Core\Config\PreExistingConfigException' with message 'Configuration       [error]
objects (field.field.message.example_create_comment.field_comment_reference,
field.field.message.example_create_comment.field_node_reference,
field.field.message.example_create_comment.field_published,
field.field.message.example_create_node.field_node_reference,
field.field.message.example_create_node.field_published,
field.storage.message.field_comment_reference, field.storage.message.field_node_reference,
field.storage.message.field_published, message.template.example_create_comment,
message.template.example_create_node, message.template.example_user_register) provided by
message_example already exist in active configuration' in
/Applications/MAMP/htdocs/drupal-8/core/lib/Drupal/Core/Config/PreExistingConfigException.php:65
```

**Comment by RoySegall** [comment]
Hmm.. That't beyond my knowledge for now. I need some more investigation on this one.

**Comment by amitaibu** [comment]
@RoySegall would be great if you could find out 😄

**Comment by RoySegall** [comment]
@mccrodp Din't we talked about this one over Message UI?

**Comment by jhedstrom** [comment]
> My work around was make the config in this module exist in "optional" folder rather than install. Is this a viable change to be added via a PR

This is a perfectly reasonable solution. If you're still up for submitting a PR, I'd be happy to review!

**Comment by mccrodp** [comment]
@jhedstrom - yep, I can do this later this week or early next week at the latest. Need to get back into the work I have remaining on [Message UI module port](https://github.com/RoySegall/message_ui/issues), it's been a while since I worked with Message. Thanks for helping close out my other issues and Message work in general!

**Comment by mccrodp** [comment]
@jhedstrom - here is a PR for this: https://github.com/Gizra/message/pull/160

**Comment by jhedstrom** [comment]
Merged. Thanks!
