### ISSUE TITLE
Messages with missing templates cannot be deleted from the Admin Messages Queue 

### ISSUE THREAD

**Issue by hyperlinked** [Gizra/message#123]
This was observed on a clean install of Drupal 8.1 and 8.2 with the message stack enabled. If you have messages that were previously created from message templates and you then delete the templates that those message werre based on, you will get an error when attempting to delete those messages from the Admin Messages Queue. 

To reproduce:
1. Enable the message stack modules including the example modules
2. Enable the forum and comment module 
3. Create a forum topic and add a few comments to generate a few messages
4. Go to /admin/structure/message and delete either the template for new nodes or new comments
5. Go to /admin/content/messages and you'll notice that the message rows that correspond to the deleted template are now blank
6. Try to delete one of those rows

The result will be an error like this:

> Error: Call to a member function label() on null in Drupal\message\Form\DeleteMultiple->Drupal\message\Form{closure}() (line 110 of /{your_path}/modules/message/src/Form/DeleteMultiple.php).

When a message template is deleted from the site, all corresponding messages should also be cleared out at the same time.

**Comment by jhedstrom** [comment]
We should probably follow core's example on this instead, and not allow the template to be deleted if there are messages using it.

This is the message core displays, for instance, when trying to delete a node type with existing content:

<img width="445" alt="screen shot 2016-10-13 at 12 53 22 pm" src="https://cloud.githubusercontent.com/assets/76833/19364697/1007a652-9144-11e6-882b-27d8fa09e0d2.png">
