### ISSUE TITLE
Entity owner interface not properly implemented

### ISSUE THREAD

**Issue by jhedstrom** [Gizra/message#129]
The `getOwnerId()` method is not properly implemented, since the `Message` entity doesn't declare the `uid` entity key. PR forthcoming.

**Comment by amitaibu** [comment]
What error did you get upon `getOwnerId()`?

**Comment by jhedstrom** [comment]
It was always returning `NULL`. In the PR over at #130 if you run just the test without the fix, you can see the that it returns null w/o that.

**Comment by amitaibu** [comment]
👍
