### ISSUE TITLE
Tag a new alpha on drupal.org

### ISSUE THREAD

**Issue by jhedstrom** [Gizra/message#132]
The drupal.org testbot apparently only pulls released versions for testing. I'm porting [Message digest](https://www.drupal.org/project/message_digest), and tests are failing since the testbot is grabbing the alpha version, rather than the dev version.

Thanks!

**Comment by amitaibu** [comment]
@jhedstrom Congrats, you now have commit access on github/ d.o 😄

**Comment by jhedstrom** [comment]
👍
