### ISSUE TITLE
Remove customized config translation handling

### ISSUE THREAD

**Issue by jhedstrom** [Gizra/message#139]
While working on #128 I am finding myself deep into the customized config entity translation forms we currently have.

I'm finding that removing them entirely still allows the config entity to be translated as expected, so figured I'd post this here to see what purpose they may have been envisioned for, or if they potentially predate some core enhancements that make them unnecessary (the original code goes back to ~2014).

**Comment by amitaibu** [comment]
I bet it's predating. Lets remove the complexity - It just needs to allow translation of the message text.

**Comment by jhedstrom** [comment]
Sounds good. I'll address this as part of #140 since it's so closely related.
