### ISSUE TITLE
Problem creating activity logs

### ISSUE THREAD

**Issue by ugintl** [Gizra/message#145]
I am using drupal 7. I have created few activity logs. All works ok, but when try to create a log for example " username started following you on github". Now this message must be logged for the "who is flagged" user and at the same time the username token must be replaced by the "who flagged it" user. The problem is that this is not happening.

When the message is logged for "who is flagged", the username is also replaced by "who is flagged" user and vice versa.

Another example is for "xyz mentioned you on github". Same problem goes here.

**Comment by RoySegall** [comment]
The user that flagged will be the owner of the message. The user that being flagged will be reference with another entity reference field.

**Comment by ugintl** [comment]
I did not get you what you are trying to say. The "message" should be received to the "person who is flagged" For e.g. If I follow you, you will receive a notification "Umair started following you on github". Now, the "you" in above example is the person who is being flagged. "Umair" flagged it and "you" was being flagged and hence "you" is the user who must receive this message and not "Umair". Having said that the Question is that How to achieve it in the message setup?

**Comment by ugintl** [comment]
@RoySegall @jhedstrom Sorry my question was incomplete. When you create a message and then you create a rule, in the rules setup, you have data selectors, this is where the actual problem is. All the story I have told you is regarding rules setup for the message. Hope you understood now. Please read the whole explanation in the context of rules setup.

**Comment by ugintl** [comment]
Please close this issue. The question was not correctly asked.
