### ISSUE TITLE
views rss error

### ISSUE THREAD

**Issue by bender-r** [Gizra/message#163]
I created view with rss display. After saving in page site.com/myfeeds i see a white screen with the words
> The website encountered an unexpected error. Please try again later.

in  logs:
> LogicException: A stray renderRoot() invocation is causing bubbling of attached assets to break. in Drupal\Core\Render\Renderer->renderRoot() (line 133 of /var/www/html/core/lib/Drupal/Core/Render/Renderer.php).

Drupal 	8.2.4 
PHP 	7.0.13
message 8.x-1.0-alpha4

**Comment by alvar0hurtad0** [comment]
@bender-r I can not reproduce.

Is the problem still there on drupal 8.2.5 ?

**Comment by jhedstrom** [comment]
Please re-open if this is still an issue (with steps to reproduce).
