### ISSUE TITLE
Example module misses depencency on Comment module

### ISSUE THREAD

**Issue by Axolotlke** [Gizra/message#170]
When the message_example module is enabled on D8 without Comment enabled, you get the following error 

`Drupal\Component\Plugin\Exception\PluginNotFoundException: The "comment" entity type does not exist. in Drupal\Core\Entity\EntityTypeManager->getDefinition() (line 133 of core/lib/Drupal/Core/Entity/EntityTypeManager.php).
Drupal\Core\Entity\EntityManager->getDefinition('comment') (Line: 115)
Drupal\Core\Field\Plugin\Field\FieldType\EntityReferenceItem::schema(Object) (Line: 445)
Drupal\field\Entity\FieldStorageConfig->getSchema() (Line: 1805)
Drupal\Core\Entity\Sql\SqlContentEntityStorageSchema->getDedicatedTableSchema(Object) (Line: 1102)
Drupal\Core\Entity\Sql\SqlContentEntityStorageSchema->createDedicatedTableSchema(Object, NULL) (Line: 1088)
Drupal\Core\Entity\Sql\SqlContentEntityStorageSchema->performFieldSchemaOperation('create', Object) (Line: 386)
Drupal\Core\Entity\Sql\SqlContentEntityStorageSchema->onFieldStorageDefinitionCreate(Object) (Line: 1415)
Drupal\Core\Entity\Sql\SqlContentEntityStorage->Drupal\Core\Entity\Sql\{closure}() (Line: 1470)
Drupal\Core\Entity\Sql\SqlContentEntityStorage->wrapSchemaException(Object) (Line: 1416)
Drupal\Core\Entity\Sql\SqlContentEntityStorage->onFieldStorageDefinitionCreate(Object) (Line: 74)
Drupal\Core\Field\FieldStorageDefinitionListener->onFieldStorageDefinitionCreate(Object) (Line: 411)
Drupal\Core\Entity\EntityManager->onFieldStorageDefinitionCreate(Object) (Line: 332)
Drupal\field\Entity\FieldStorageConfig->preSaveNew(Object) (Line: 286)
Drupal\field\Entity\FieldStorageConfig->preSave(Object) (Line: 434)
Drupal\Core\Entity\EntityStorageBase->doPreSave(Object) (Line: 389)
Drupal\Core\Entity\EntityStorageBase->save(Object) (Line: 259)
Drupal\Core\Config\Entity\ConfigEntityStorage->save(Object) (Line: 364)
Drupal\Core\Entity\Entity->save() (Line: 637)
Drupal\Core\Config\Entity\ConfigEntityBase->save() (Line: 321)
Drupal\Core\Config\ConfigInstaller->createConfiguration('', Array, 1) (Line: 220)
Drupal\Core\Config\ConfigInstaller->installOptionalConfig(Object, '') (Line: 138)
Drupal\Core\Config\ConfigInstaller->installDefaultConfig('module', 'message_example') (Line: 75)
Drupal\Core\ProxyClass\Config\ConfigInstaller->installDefaultConfig('module', 'message_example') (Line: 248)
Drupal\Core\Extension\ModuleInstaller->install(Array, 1) (Line: 83)
`

This is because the config for the comment reference field gets imported on install.
Adding comment (and node) as dependency solves the issue.

**Comment by jhedstrom** [comment]
This was fixed some time ago.
