### ISSUE TITLE
Purge logic is far too limited for sites with large numbers of messages

### ISSUE THREAD

**Issue by jhedstrom** [Gizra/message#193]
On sites that expose message entities to the UI, it is necessary that a copy of each message be saved **per-user**, similarly if a site is using the [Message Digest](https://www.drupal.org/project/message_digest) module, a copy also needs to be saved per-recipient.

This results in very large numbers of message entities, and the current purge logic defaults to limiting deletions to 100-per-cron run. While this is configurable (not via the UI), even upping it to 1000 would not be sufficient, and any higher than that the process would probably run into memory issues since we're using the API for deletions.

**Proposed solution**

Remove the quota entirely and utilize the job queue system to queue all message entities qualified for deletion in batches of 100.

**Comment by amitaibu** [comment]
Yeah, solution makes total sense.

**Comment by kevin-dutra** [comment]
When #198 makes it in, I'll toss a PR out there for this issue. (That issue includes the necessary queue worker, so it'll reduce duplication.)
