### ISSUE TITLE
Message cleanup on entity delete purges more than it's supposed to

### ISSUE THREAD

**Issue by kevin-dutra** [Gizra/message#199]
The logic that purges messages upon deletion of an entity does not check the target type of the entity reference fields it looks at, causing it to delete messages that it shouldn't. As an example:

Let's say I have 2 main flavors of messages -- one that deal with comments, and so they have a comment entity reference field, and another that deal with nodes, and so they have a node entity reference field.

The site plugs along and messages have been created for a number of different nodes and comments. Then I go to delete node 123. 

**Expected result**
All messages that reference node 123 are also deleted.

**Actual result**
All messages that reference node 123 **or** comment 123 are also deleted.

**Comment by jhedstrom** [comment]
Wow, that's no good at all.
