### ISSUE TITLE
Is there any plan to add support to "Fan out on write" instead of the current views-based "Fan out on read" approach?

### ISSUE THREAD

**Issue by wundo** [Gizra/message#2]

**Comment by amitaibu** [comment]
What do you mean by fan out?

‫ב-5 בנוב 2014, בשעה 20:59, ‏wundo notifications@github.com כתב/ה:‬

**Comment by wundo** [comment]
http://rubanm.tumblr.com/post/59561467766/write-based-fan-out-vs-read-based-fan-out :)

**Comment by amitaibu** [comment]
I understand. No, no such plan -- it's outside of the scope of Message itself, but I'd love to see an implementation example.

**Comment by amitaibu** [comment]
- Thanks for using the Gtihub queue :)
