### ISSUE TITLE
Illegal string offset MessageTemplate.php

### ISSUE THREAD

**Issue by ordavidil** [Gizra/message#209]
After updating from `8.x-dev-1.x#4b8551c` to `8.x-1.0-beta2` I get the next two errors every time a message is being loaded:
```
Illegal string offset 'format' MessageTemplate.php:275                                                                                                                       
Illegal string offset 'value' MessageTemplate.php:274                                                                                                                        
```

When visiting `admin/content/messages` I get this for each existing message
1. ![message___ideal-ist](https://user-images.githubusercontent.com/5985683/32829642-55e290b0-c9fb-11e7-9dcc-6feb2d96518d.gif)

1.  ![message___ideal-ist](https://user-images.githubusercontent.com/5985683/32829625-489006fe-c9fb-11e7-8b42-5114a2c9c604.gif)

**Comment by ordavidil** [comment]
After digging a bit, I've found [this commit](https://github.com/Gizra/message/commit/65925ef4149c34a87c721c69d4b0ccbee963982c#diff-cbb8327539b3bb07e623ac9d85d57052R265) 

It seems that the structure probably has been changed since the version I've used, but from what I've noticed, after this change there wasn't any `hook_update_N` that handles/update the structure of the existing messages.

**Comment by amitaibu** [comment]
Yeah, sorry but there are no `hook_update_N` until a final release

**Comment by amitaibu** [comment]
You will probably have to re-create the Message templates based on the updated version, and re-export.
