### ISSUE TITLE
Composer json references incorrect version of coder

### ISSUE THREAD

**Issue by NewZeal** [Gizra/message#227]
This has fatal consequences when installing in a purely composer driven environment.  i.e. the module does not install and cannot be installed.
The entry in composer json
```
"require-dev": {
    "drupal/coder": "^8.2"
  }
```
References non existent coder 8.x

See [patch](https://www.drupal.org/files/issues/2018-07-06/message-composer-require-fix.patch)

**Comment by jhedstrom** [comment]
I think this has been resolved elsewhere.
