### ISSUE TITLE
Allow "message" twig template message.html.twig to be discoverable, perhaps using hook_theme

### ISSUE THREAD

**Issue by mccrodp** [Gizra/message#31]
Further to discussion, it looks like message.html.twig is unused unlike it's tpl.php predecessor in D7.

It should be removed if so and perhaps we can include in Message UI if needed.

**Comment by amitaibu** [comment]
it should be allowed to override the twig file, the same as we allowed for D7

**Comment by mccrodp** [comment]
Ok, that makes sense. Does [`hook_theme`](https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Render!theme.api.php/function/hook_theme/8) from D7 (shown below) need to be ported then to make this template discoverable?

```
/**
 * Implements hook_theme().
 */
function message_theme() {
  $info['message'] = array(
    'render element' => 'elements',
    'template' => 'message',
  );

  return $info;
}
```

In _message_ui_ for D8 it was not calling the twig template when I passed "message" to the render array.
