### ISSUE TITLE
Undefined index: en in Drupal\message\MessageViewBuilder->view() : line 43

### ISSUE THREAD

**Issue by mccrodp** [Gizra/message#32]
<code>Notice: Undefined index: en in Drupal\message\MessageViewBuilder->view() (line 43 of modules/message/src/MessageViewBuilder.php).</code>

There may be a problem with obtaining the partials (Line : 25)

<code>
$partials = $entity->getType()->getText(NULL, array('text' => TRUE));
</code>

There <code>entity_get_display</code> is also deprecated on Line : 39.

**Comment by mccrodp** [comment]
I think this is a duplicate of https://github.com/Gizra/message/issues/35 now that I look at it, they are definitely related. I believe it is the issue (and possible fix) I have detailed more recently here also : https://github.com/Gizra/message/pull/37#issuecomment-159229859

**Comment by jhedstrom** [comment]
I think this has been fixed. Please re-open if this isn't the case.
