### ISSUE TITLE
time for a new supported 7.x release?

### ISSUE THREAD

**Issue by bradbulger** [Gizra/message#4]
It's been almost a year and a half since 1.9.

**Comment by wundo** [comment]
I agree with @bradbulger that a new release would come handy, @amitaibu could you define a roadmap of what needs to fixed before releasing a new stable version?

**Comment by amitaibu** [comment]
I'll roll a new release in a couple of days.

**Comment by wundo** [comment]
thanks

**Comment by amitaibu** [comment]
@RoySegall would you mind creating a release please (on GitHub + d.o)

**Comment by RoySegall** [comment]
Sure. After merging in #6 should i create 2.0?

**Comment by amitaibu** [comment]
> After merging in #6 should i create 2.0?

no, before.

Also, not a 2.0 - but 1.10
