### ISSUE TITLE
Diff from jhedstrom/message:update-rc1 and update-travis branch re: test errors

### ISSUE THREAD

**Issue by mccrodp** [Gizra/message#46]
@RoySegall / @jhedstrom I did a diff between these branches (attached).

If you `cat update-rc1_update-travis_diff.txt` it should display with color. Can you please let me know which changes should be preserved and if you can see any issues relating to this test error referenced from https://github.com/Gizra/message/pull/39#issuecomment-171214723

Following this I'll create a PR as requested in the issue above.
[update-rc1_update-travis_diff.txt](https://github.com/Gizra/message/files/91727/update-rc1_update-travis_diff.txt)

**Comment by mccrodp** [comment]
There were no differences in `.tavis.yml` file.

However, on inspecting Travis report, some calls to a static method on an interface which is now fixed. I have made a start on getting all tests working in PR: https://github.com/Gizra/message/pull/47

This issue can be closed now as I'll update via the PR above.

**Comment by RoySegall** [comment]
Closing. Thanks for the work.
