### ISSUE TITLE
Make Message entity revisionable

### ISSUE THREAD

**Issue by mccrodp** [Gizra/message#5]
It looks like Message entity does not provide revisions. 

Would this affect many areas of the code if we follow the documentation to <a href="https://www.drupal.org/node/1892478">make an entity revisionable</a>?

Is this something that can make it into Message on D7, through a contributed patch or otherwise, or will it make it into D8 only now?

**Comment by amitaibu** [comment]
I can't think of a _real_ use case where Message would need to be revisionable. Anyway, this can probably be done in contrib.

**Comment by mccrodp** [comment]
Thanks, this makes sense as contrib if it could be done there, using `hook_entity_info_alter` and whatever else is needed.

The use case came about on a [Message Private issue](https://www.drupal.org/node/2367729#comment-9480579) as a work around providing accessible timestamps on field instances, i.e. - a field added per message revision where the message entity is a message thread. 

I don't know how valid that method is and I decided against it anyway, but revisionable Messages could be used in [Message Private](https://www.drupal.org/project/message_private) in future, so it's good to know it may be possible in contrib as "Message Revisions" or similar. Thank you.
