### ISSUE TITLE
Decopule message arguments in ctools plugin

### ISSUE THREAD

**Issue by RoySegall** [Gizra/message#6]
Until now the message arguments were saved in the DB into the message objects. The disadvantages of it are:
1. The information for each message, value or callback, and if we need to maintain the value we need to iterate over the messages and update the value or change the arguments.
2. The information is shared to all the messages form the same bundle. Store this data in the DB for each message is a pretty much over kill and can live outside the DB.

This will affect the 8.x-1.x branch as well.

**Comment by wundo** [comment]
<blockquote>2. The information is shared to all the messages form the same bundle. Store this data in the DB for each message is a pretty much over kill and can live outside the DB.</blockquote>

Could you elaborate on that?
I have spent the last two days trying to wrangle a patch that allows me to not store the message text itself on the database at all (I would store only the arguments). 

I'm not sure if it would be a good approach or not, is this patch a step on that direction? 
Do you think this is a good approach?

**Comment by amitaibu** [comment]
> Could you elaborate on that?

This PR address the cases where you would hardcode the callback functions in the message's `arguments` - just so they can be invoke upon $message->getText(). This PR will allow to add those callbacks on the fly via hook_entity_load() - thus avoiding saving the same data over and over again per message

**Comment by RoySegall** [comment]
@amitaibu Can you review the PR? 10x.
