### ISSUE TITLE
Add an Alpha release and push 8.x repo back to drupal.org

### ISSUE THREAD

**Issue by jhedstrom** [Gizra/message#67]
I think the current state of this module is ready for an alpha. It would also be good to push the current repo back up to drupal.org for greater visibility.

**Comment by amitaibu** [comment]
I'm going to have some time next week to get my hands a little dirty with Message, so lets wait with alpha a few more days, to give me a chance to go over it :smile:

**Comment by amitaibu** [comment]
> It would also be good to push the current repo back up to drupal.org for greater visibility.

Yeah, that can already by done

**Comment by jhedstrom** [comment]
Bump :)

Perhaps a milestone could be added and issues/PRs that are blocking an alpha? It would be really good to get some releases over on d.o. I think for visibility of the message stack + Drupal 8.

**Comment by amitaibu** [comment]
Good idea, I'll open the issues and tag them. I'll update here once done.

**Comment by amitaibu** [comment]
I've added a `Release blocker` label.

Issues: https://github.com/Gizra/message/issues?q=is%3Aissue+is%3Aopen+label%3A%22Release+blocker%22
PR: https://github.com/Gizra/message/pulls?q=is%3Apr+is%3Aopen+label%3A%22Release+blocker%22

**Comment by jhedstrom** [comment]
I don't know that any of the remaining `Release blocker` issues need block an alpha. Bug fixes and API _additions_ are certainly allowed in alpha. Tagging an alpha would allow the tracking issue (https://www.drupal.org/node/2592937) to be set to Needs Review, which would be good at this point I think.

**Comment by amitaibu** [comment]
Sure - https://www.drupal.org/project/message/releases/8.x-1.0-alpha1

Thanks for the good advices!
