### ISSUE TITLE
Move tests under a single place

### ISSUE THREAD

**Issue by amitaibu** [Gizra/message#73]
@RoySegall Some tests are under `tests`, and some are under `src/Tests`. Is there a reason, or an oversight?

**Comment by bojanz** [comment]
Tests that are run by phpunit (unit/kernel/functional) are under tests. Simpletests are under src/Tests.

**Comment by amitaibu** [comment]
You are right. What threw me off was that `MessageTokenTest` was duplicated and was under `src/Tests` as-well.

I went over the rest of the tests, and they are indeed in place.
