### ISSUE TITLE
Update the token integration

### ISSUE THREAD

**Issue by amitaibu** [Gizra/message#86]
Currently when enabling the token module we are not getting tokens related to Message. We used to het it via D7's entity_token.

@RoySegall @jhedstrom do you happen to know if there's a replacement for this?

My goal is to remove as much as possible from `message_example_token_info()`

**Comment by amitaibu** [comment]
to clarify, what we are missing now that we got for free from entity_token, was also the entity-references integration, which are now missing.

**Comment by bojanz** [comment]
The work needs to happen in Token module:
https://www.drupal.org/node/2621598
https://www.drupal.org/node/2493567

**Comment by jhedstrom** [comment]
@amitaibu There is also https://www.drupal.org/node/2493559 in the token module.

**Comment by amitaibu** [comment]
:+1: 

(off topic: Before the tokens I'm going to invest some time in making sure we got the Message type schema +translation right. I have a feeling we could do some cleanup in the existing code.)

**Comment by bojanz** [comment]
It might make a lot of sense to reuse the new tokens developed by Rules:
http://d8rules.org/news/d8rules-reaches-milestone-2

This would mean adding a dependency to the currently empty [TypedData](https://www.drupal.org/project/typed_data) module, compared to depending on Token for plan A. In both cases a dependency will be needed.

**Comment by amitaibu** [comment]
Token module isn't a hard dependency anyway.

**Comment by bojanz** [comment]
Isn't it? Without it you don't get what entity tokens gave you in D7, which was a non-optional part of the experience.

**Comment by amitaibu** [comment]
you can also in D7 to set the arguments yourself without the need of a token. You can in fact also have the arguments be a function so you can calculate the values on the fly.

I can do a quick skype with you to go over it if you want :)

**Comment by jhedstrom** [comment]
Is this a beta-blocker? It's the only remaining issue in the milestone :)

**Comment by amitaibu** [comment]
I guess it could be pushed for after the 1st beta, but it should be addressed eventually.

**Comment by jhedstrom** [comment]
The 3 token issues noted above have been resolved, so I think this issue is now fixed?
