### ISSUE TITLE
Consider alternative terminology

### ISSUE THREAD

**Issue by bojanz** [Gizra/message#98]
So, at this point we've been using Message for 4 years in Kickstart and outside of it, as well as helping the community use it.

There has always been some level of confusion regarding the relationship between Messages and Message Types. While types are standard Drupal terminology, they usually exist only to provide fields. Here, they have another purpose: to provide the template.

My gut feeling is that it would be much clearer for Message Types to be called Message Templates. That's their primary purpose, they hold the template, which then gets the tokens replaced, and then used (and / or saved as a message). The bundle aspect of it is secondary (especially since many/most messages have a need for the same two fields: the source entity, the body).

I'd also rename Message Type Categories to Message Template Groups, since it feels like "group" is more standard for this purpose than "category".

**Comment by amitaibu** [comment]
This is a great suggestion! I think template defiantly makes more sense for non-devs.

**Comment by RoySegall** [comment]
@amitaibu Why not, after the #97, @HelenaEksler will take this one?

**Comment by amitaibu** [comment]
👍

**Comment by HelenaEksler** [comment]
> I'd also rename Message Type Categories to Message Template Groups, since it feels like "group" is more standard for this purpose than "category".

@amitaibu I see its called just `message_category` and there is no functionality for this (just 2 hooks). I can rename it there to `message_group` or I can leave it as is till we decide if we need this at all. How do you think?

**Comment by amitaibu** [comment]
lets leave message category for now, and deal only with message types

**Comment by amitaibu** [comment]
Done!

**Comment by amitaibu** [comment]
(and pushed to d.o.)
